### ISSUE TITLE
Wrong URL for example of VAT number validation

### ISSUE THREAD

**Issue by sdvb** [quaderno/quaderno-api#10]
Hi, 

The URL in the shell example on the right side of the page [here](https://quaderno.io/docs/api/?shell#validating-vat-numbers) seems incorrect, and should be https://ACCOUNT-NAME.quadernoapp.com/api/taxes/validate.json?country=IE&&vat_number=IE6388047V instead.

Stefan

**Comment by xxswingxx** [comment]
Thanks for notifying the issue. Fixed in b94c5b431118a7caaf8733a9864ef7e665ec94a9.
