### ISSUE TITLE
Transition to 20210316 is as easy as pie - Is it?

### ISSUE THREAD

**Issue by pawellen** [quaderno/quaderno-api#29]
It would be, but you mislead developers putting false statements in migration guide.

1) For calculating tax rates, altough the new endpoint accepts many more parameters, just changing the URL from /taxes/calculate to /tax_rates/calculate will do. 

This is NOT TRUE. Parameter names ware changed. I lost a lot of time because of this (example: country => to_country and many more)

**Comment by polimorfico** [comment]
Hi there! Thanks for reaching out. We've updated our API to support old parameter names. 
Please let us know if you have any questions or comments. Happy to help!
