### ISSUE TITLE
/tax_rates/calculate - does not return VAT stakes according to new EU law

### ISSUE THREAD

**Issue by pawellen** [quaderno/quaderno-api#32]
GET /tax_rates/calculate endpoint 
Tax calculate endpoint doesn't return VAT stakes according to new EU law. According to this article on your website:
https://www.quaderno.io/blog/oss-or-ioss-eu-vat-one-stop-shop-rules-for-e-commerce
from this day (01.07.2021) new EU law applies. But you did not mention anything about your API, do we need to reconfigure anything? Currently I am checking results returned by this endpoint and it does not work correctly.

ps. you are providing a lot of information about law changes but almost none of thechnical detials how to apply them in your platform :(

**Comment by polimorfico** [comment]
Hi there! You don't need to do anything apart from adding the EU OSS / IOSS jurisdiction in your Quaderno account if you're required to.

Please let me know what issues you've found to check them out.
