### ISSUE TITLE
Generating Webhook signatures

### ISSUE THREAD

**Issue by pat** [quaderno/quaderno-api#4]
Just looking for some clarification on how to generate webhook signatures.

Firstly, it seems that all parameters come through as standard form params (`application/x-www-form-urlencoded`). There's no JSON values at all - `data[object][id]=123` instead of `data={"object":{"id":123}}`. The initial docs indicate at least `data` returns JSON, and the output provided had me initially thinking the entire request body would be JSON (`application/json` instead of `application/x-www-form-urlencoded`).

Secondly, when it comes to sorting parameters, is it by key in a non-nested sense? i.e. should it be by `data[object][id]`? By the entire key and value (`data[object][id]=123`)? Or something else? Non-nested keys are what I've been trying, but no luck yet.

My current implementation can be found here: https://github.com/inspire9/quadhook - the tests pass, but when I've tried it with a real request from a webhook I've just generated and received a call on, the signature does not match.

**Comment by xxswingxx** [comment]
The JSON value is pretty much a bug. The data should be parsed as a JSON string. It should be returning json from now on. Thanks for reporting it! 

On the other hand, the signature generation relies on having a hash structured params. The sorting is done on the hash first level, non-nested  sense, so in most cases the structure will not be modified. Basically it should sort two keys: `event_type` and `data`.

As far as I've tested, frameworks like Rails when receiving the post content, adds extra keys to the parsed hash like `action` or `controller` which should be removed before checking the signature (on the hash first level there are only `event_type` and  `data`)

**Comment by pat** [comment]
Given the full request body is now JSON (not just `data`), translating it into params, sorting (but only one level deep?) and then hashing is a bit messy. Why not just use the request body as it's sent (appended to the webhook's URI) instead? That avoids the sorting complications completely.

Otherwise, can you provide a step-by-step example of a sample payload and how you expect it to look before generating the HMAC SHA1?

For the record, this isn't Rails, but pure Rack, so there are no additional parameters being added.

**Comment by xxswingxx** [comment]
I expect the endpoint to have the JSON parsed into a manipulable data structure, like a `ruby` hash or a `php` array. With that in hand you can do the following `ruby` example:

```ruby
hook_data = {
  "event_type" =>"invoice.created", 
  "data" =>
  {
    "object" =>
    {
      "id"=>"26", 
      "contact_id"=>"2", 
      "number"=>"XX00001281", 
      "issue_date"=>"2014-04-22", 
      "contact_name"=>"Hello Test APP", 
      "currency"=>"EUR", 
      "gross_amount_cents"=>"1000", 
      "total_cents"=>"1000", 
      "amount_paid_cents"=>"0", 
      "po_number"=>"", 
      "due_days"=>"", 
      "due_date"=>"", 
      "payment_details"=>"", 
      "notes"=>"", 
      "permalink"=>"20efc2ea3e9bc7060aaab1dd8c2c6b85a427b30d", 
      "state"=>"draft"
    }
  }
}

auth_key = 'theGeneratedKeyForTheSubscribedHook' 
url = 'https://example-site.com/endpoint' # The url you've set for the webhook
digest = OpenSSL::Digest.new('sha1')

signature = Base64.encode64(OpenSSL::HMAC.digest(digest, auth_key, "#{self.url}#{Hash[params.sort].flatten.join}")) # If everything is OK, this value shold be exactly the same as the passed in the header
```

**Comment by pat** [comment]
Thanks, that seems to have done the trick (though, slight typo in your answer - `params` instead of `hook_data` in the final line).

I don't think you need to use `Hash[]` either - `hook_data.sort.flatten.join` does the trick for me.

**Comment by joealcorn** [comment]
Hi all,

We're having trouble implementing this in Python.

We have an object like this

```
hook_data = {
  "event_type" =>"invoice.created", 
  "data" =>
  {
    "object" =>
    {
      "id"=>"26", 
      "contact_id"=>"2", 
      "number"=>"XX00001281", 
      "issue_date"=>"2014-04-22", 
      "contact_name"=>"Hello Test APP", 
      "currency"=>"EUR", 
      "gross_amount_cents"=>"1000", 
      "total_cents"=>"1000", 
      "amount_paid_cents"=>"0", 
      "po_number"=>"", 
      "due_days"=>"", 
      "due_date"=>"", 
      "payment_details"=>"", 
      "notes"=>"", 
      "permalink"=>"20efc2ea3e9bc7060aaab1dd8c2c6b85a427b30d", 
      "state"=>"draft"
    }
  }
}
```

From what I gather, the only sorting done is the top level, the `event_type` and `data` keys. This leaves us with a nested hash which we do not know what to do with. In your ruby example, the following happens.

We first flatten the top level keys into a list, resulting in this

```
["event_type", "invoice.created", "data", {"object"=>{"id"=>"26", "contact_id"=>"2", "number"=>"XX00001281", "issue_date"=>"2014-04-22", "contact_name"=>"Hello Test APP", "currency"=>"EUR", "gross_amount_cents"=>"1000", "total_cents"=>"1000", "amount_paid_cents"=>"0", "po_number"=>"", "due_days"=>"", "due_date"=>"", "payment_details"=>"", "notes"=>"", "permalink"=>"20efc2ea3e9bc7060aaab1dd8c2c6b85a427b30d", "state"=>"draft"}}]
```

Then we join them, which will call `object.to_s` when it hits the hash, resulting in this.

```
"data{\"object\"=>{\"id\"=>\"26\", \"contact_id\"=>\"2\", \"number\"=>\"XX00001281\", \"issue_date\"=>\"2014-04-22\", \"contact_name\"=>\"Hello Test APP\", \"currency\"=>\"EUR\", \"gross_amount_cents\"=>\"1000\", \"total_cents\"=>\"1000\", \"amount_paid_cents\"=>\"0\", \"po_number\"=>\"\", \"due_days\"=>\"\", \"due_date\"=>\"\", \"payment_details\"=>\"\", \"notes\"=>\"\", \"permalink\"=>\"20efc2ea3e9bc7060aaab1dd8c2c6b85a427b30d\", \"state\"=>\"draft\"}}event_typeinvoice.created"
```

This causes issues because this format not easily reproducible in programming languages other than ruby as it relies on ruby's default hash serialization behaviour rather than well defined json (sorted, space removed, etc).

Firstly it's using the ruby notation for mapping keys to values, `key => value`. Secondly hash tables/dicts are unordered, so the result will vary depending on the implementation.

This basically makes it impossible for us to authenticate webhooks in Python.

@pat's suggestion above makes a lot more sense, generate the signature from the raw request body as you send it. That prevents us from having to touch the data at all to verify the source.

Any guidance is appreciated.

**Comment by xxswingxx** [comment]
@joealcorn, we've just updated the webhook data verification for webhooks created starting today (2015-05-22), now you can use the request body appended to the url to generate the signature. 

```ruby
auth_key = 'theGeneratedKeyForTheSubscribedHook' 
url = 'https://example-site.com/endpoint' 
request_body =  "{\"event_type\":\"invoice.created\",\"data\":{\"object\":{\"id\":\"26\",\"contact_id\":\"2\",\"number\":\"XX00001281\",\"issue_date\":\"2014-04-22\",\"contact_name\":\"Hello Test APP\",\"currency\":\"EUR\",\"gross_amount_cents\":\"1000\",\"total_cents\":\"1000\",\"amount_paid_cents\":\"0\",\"po_number\":\"\",\"due_days\":\"\",\"due_date\":\"\",\"payment_details\":\"\",\"notes\":\"\",\"permalink\":\"20efc2ea3e9bc7060aaab1dd8c2c6b85a427b30d\",\"state\":\"draft\"}}}" 

digest = OpenSSL::Digest.new('sha1')
signature = Base64.encode64(OpenSSL::HMAC.digest(digest, auth_key, "#{url}#{request.body}")) # If everything is OK, this value shold be exactly the same as the passed in the header
```

For legacy purposes (older webhooks) we also kept the old method but it would be ideal to use the new one to prevent issues like this one. 

@pat, maybe you are interested to update your endpoint.

Thanks for your patience and suggestion guys.

**Comment by joealcorn** [comment]
That's great, thanks @xxswingxx.

Presumably the signature is passed in a different header to preserve backwards compatibility? If so, which?

**Comment by seanpreston** [comment]
Thanks guys!

**Comment by xxswingxx** [comment]
@joealcorn, no it doesn't, in our side, we check the creation date of the webhook in order to decide which method we should use to generate the signature, the rest is the same. So if you want to use the new method you should remove the current webhook (I think it was created yesterday) and create a new one.

**Comment by seanpreston** [comment]
Hey @xxswingxx, I've just yesterday made time to revisit this,

Presumably the fields in `request_body['data']['object']` must also be in the order you have specified above?

**Comment by xxswingxx** [comment]
@seanpreston, not anymore really. Since this issue was closed, we've increased the details of the object so you may find new fields. 

You should not rely on the above example exact order.

**Comment by seanpreston** [comment]
The reason I asked is because I noticed that the ordering you had above is different to the ordering in Python. Perhaps this is Python implicitly ordering the dict? Would you recommend using the raw post data instead?

**Comment by xxswingxx** [comment]
The raw post body is a JSON string so the order should be invariable. If you need to verify the webhook, I should say yes, I would definitely recommend you to use the raw data instead an specific object processed by the language.
