### ISSUE TITLE
How filter invoices 

### ISSUE THREAD

**Issue by masalinas** [quaderno/quaderno-api#5]
How I can query invoices for a contact and a issue_date??

using curl my query is:

`curl -u <MY_API_KEY> -X GET 'https://<MY_HOST>.quadernoapp.com/api/v1/invoices.json?contact=<MY_ID>&issue_date=2016-02-08'`

The query only use the first parameter in this case contact to obtain the result the second one, issue_date is not used for your API, what is wrong???

**Comment by xxswingxx** [comment]
@masalinas You can use the `date` parameter like this `GET /invoices.json?date=DATE1,DATE2`. `DATE1` and `DATE2` define a date range separated by a comma

**Comment by xxswingxx** [comment]
@masalinas Feel free to close this issue if you have solved your issue. Thansk!

**Comment by masalinas** [comment]
Ok thanks it's resolved!
