### ISSUE TITLE
Should we add the evidences endpoint?

### ISSUE THREAD

**Issue by xxswingxx** [quaderno/quaderno-api#8]
Some people might need use the evidences endpoint manually (people who use Braintree for one-off charges and want to have invoices and be VAT compliant). 

The current amount of people using this API endpoint on purpose (there are some people using this endpoint without knowing it through the plugins created by @polimorfico) is minimal but having but to explicitly explain this to users on the support emails is a little PITA and even a bit confusing for the interested users as the API docs are not a complete knowledge compendium about the API.

On the other hand I'm not sure if adding this to the docs could lead to more issues to the rest of the API users as they may not know when to use the evidences or the utility of this object.

What do you guys think?

**Comment by polimorfico** [comment]
I think we should add this. It's going to be a more and more popular request and the endpoint does already exist. Let's make it public on the docs.
